[package]
name = "anvil-calc"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Optimal Minecraft anvil enchantment order calculator"
repository = "https://github.com/ViRb3/anvil-calc"
homepage = "https://virb3.github.io/anvil-calc/"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
yaml_serde = "0.10.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.126"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
