config:
  # Combining books is free when using Enchantment Library (Apotheosis)
  books_free: false
input:
  # [name, level x multiplier, penalty]
  # https://minecraft.fandom.com/wiki/Anvil_mechanics#Costs_for_combining_enchantments
  items:
    - ["boots", 0x0, 0]
  books:
    - ["soul speed", 3x4, 0]
    - ["thorns", 3x4, 0]
    - ["feather falling", 4x1, 0]
    - ["depth strider", 3x2, 0]
    - ["protection", 4x1, 0]
    - ["unbreaking", 3x1, 0]
    - ["mending", 1x2, 0]
