config:
  # Combining books is free when using Enchantment Library (Apotheosis)
  books_free: false
input:
  # name, value (level*multiplier), work count, extra cost
  # https://minecraft.fandom.com/wiki/Anvil_mechanics#Costs_for_combining_enchantments
  items:
    - ["pickaxe", 0, 0, 0]
  books:
    - ["soul speed", 12, 0, 0]
    - ["thorns", 12, 0, 0]
    - ["feather falling", 4, 0, 0]
    - ["depth strider", 6, 0, 0]
    - ["protection", 4, 0, 0]
    - ["unbreaking", 3, 0, 0]
    - ["mending", 2, 0, 0]
#    - ["coolness", 2, 0, 0]
